env:
  browser: true
  es6: true
parser: babel-eslint
extends:
  - google
  - plugin:react/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
rules:
  max-len:
    - error
    - code: 100
      ignoreStrings: true
  require-jsdoc:
    - off
  react/jsx-uses-react:
    - error
  no-invalid-this:
    - off
